site :opscode

metadata

cookbook "nodejs"
cookbook "application"
cookbook "database"
cookbook "git"
cookbook "nginx"
cookbook "postgresql"
cookbook "yum"
cookbook "unicorn"
cookbook "application_nginx"
cookbook "vim"
cookbook "build-essential"
cookbook "rbenv", :git => "git://github.com/fnichol/chef-rbenv.git"
