site :opscode

metadata

cookbook "application"
cookbook "database"
cookbook "git"
cookbook "nginx"
cookbook "postgresql"
cookbook "yum"
cookbook "unicorn"
cookbook "application_nginx"
cookbook "application_ruby"
