# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = "nest-berkshelf"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "Berkshelf-CentOS-6.3-x86_64-minimal"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://dl.dropbox.com/u/31081437/Berkshelf-CentOS-6.3-x86_64-minimal.box"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :private_network, ip: "33.33.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.

  # config.vm.network :public_network

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  config.ssh.max_tries = 40
  config.ssh.timeout   = 120

  # The path to the Berksfile to use with Vagrant Berkshelf
  # config.berkshelf.berksfile_path = "./Berksfile"

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_solo do |chef|
    chef.json = {
	:nest => {
	  :repository => "gitolite@samba01.vail:webteam/jchef",
	  :app => "jchef",
	  :migrate => false,
	  :database => true,
	  :deploy_key => "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA3Sr3IqzQ5soMzVbUSYxgrw4SPJkpP0lBjI1nnSi6SIX6kdgM
SyplRhiWYzj2JH26Ni/wd0/K8xU9rHeEmKjmvPtZhNO8j8/dDcD1DOKrXvvXGsTx
3KltJVEhwaE5txGR802I5GG3Z1UU/KLRg3HAf9/+UGDCxwbKuGqeKJIbq2rhLtHQ
FrxaD040rvcELNY+vinX1F4mGRs1ku6Dye+UZ45etcGnUUrYGMR2YAH3M3iG/emC
vBY0MlRqF7fwfoJUyFL0indXzbAvFHxsI741LiiVPjz0vNl2iGxdD3w2fxBVJcDR
TKMRfRvmEDKs0uIORoCjv1ORFV15NgrDs7cT0QIDAQABAoIBAGxrRpFCBHpOrC3x
FcokPbUzAa+hKX4zrCV5oESDlaY9v5LFRWmHk/Pj0706TDehRqqPn6Ltg8DcNcqZ
IHAxxEL6OG0L2xDoxiWa5MX3TCkY7d7akvIoQDAd8J1aKs/aliCebq/+UwkdxVb/
fhOgrMxDAwlmFbW5V6FF6than6PMrKiWp045bgiwvsJWWluI6dh4OgwA00IoCrZJ
qcTRGFyqdpKnhJo3A7IM7CNC1dH2vPOFIyNNpFfTw21WrAYE61b1bXY5RQKRiNPL
W0Hx/KW1X5nd5ULFGyb59f/vJqBIM5BWuff4uGHo/l7pw/takYvxMUP2HmD+Ro/L
ceEePc0CgYEA+Ju0VMuDdYLEjksRIXEryYbVdP71W8jjUWKbgwB++EPZUw/Ma3GX
LqeA/+B4+7SNGjwO5IXk/RfdYUBvkOz0iFY9HwY4wR02sRRCJQWQ1A5l21fNUcHy
rOPOx8lt60ixTf4Yyg4FXCg9KsefbmJYOaL5bAKRVC9tSWb5AZN/TbsCgYEA475l
mq6nWzaLdIgMs7qAFDrf/vCzuQm+XeERWea/p5+yT3lh0ynd1Mw/3h4S+FmRQWAW
2otymTz3mizi3H3Cyx2rkH9OZWHgzpclr+ZNEqdn+MzzAp6DZAmhN4TB/fzG8+Yl
YmOn0T9ogKcmloVlLUhrfHKJyYXwIGXAVQKpheMCgYAQcMuWJ/dDmChDeLdjTMam
hyIqoIm9TiWqRikemrPK20HN+md8W4Cx9yXSxhd6HdCPAZXCixA/pIphWg+GuATb
10gnexPZwYLSZxKQvDN9so4N2Vqco4TW5iHQmIOKYb5H+BvPkOnN1GNnJthmRl6r
QRnZiLnvpUtG5WZmMkji7QKBgH7F4IcfS7ehgDVo+jEd0ufv8fpXAKQzAU3+2ArE
QNFNOxO0TLkf6ATpgW/iK8slCI9srqwOzcbxQh8Hd20ncERiirsPspMKzfoR9v+Y
YjTNDTpY07kUha0tExn1g4sfp5vi89J2CNeYxVJAOWG2daCkXHjUxVBxhz5xhYOM
zNLjAoGBAMDScQClWPOMBxYPEKUP944CRYcpRn9UUH9SKVCVB2uHVIMP7D6bKCse
th1oYRr/bBZzPTq3STKj0MqX8VXzhOuWkot1+1notQnrr34gtG0AP0uOXLkt/aoy
VVHQWQCHrnY/s3GmtlcDse76nZRqh54FXoWkUimXmZpxc3J3YTC2
-----END RSA PRIVATE KEY-----"
	}
    }

    chef.run_list = [
      "recipe[nest::justin]"
    ]
  end
end
